slam_controller:
  node_management:
    always:
      # SLAM
      - slam_mcl
      - lap_counter
      - map_publisher

      # Control
      - pure_pursuit_control
      - path_publisher
      # - path_smoother

slam_mcl:
  path_to_map: "/ugr/car/map/global"
lap_counter:
  finishpoint:
    x: 35
    y: 0 
  laps: 1
  distance_after: 0
  finishRange: 3
map_publisher:
  map_pkg: "slam_simulator"
  map: "/maps/acceleration_75m.yaml"
speed:
  target: 14 # 50 km/h
  LC_adaptive_velocity: False
pure_pursuit:
  change_index: False
  world_frame: "ugr/map"
  speed_start: 2
  speed_stop: 15
  distance_start: 2
  distance_stop: 6
front_wheel_feedback:
  change_index: False
  world_frame: "ugr/map"
  Kp: 0.8
  Ki: 0.01
  Kd: 0.01
mpc:
  change_index: False
  minimal_distance: 3
  world_frame: "ugr/map"
path_publisher:
  package_path: "path_publisher"
  path: "/paths/straight_L75.yaml"
