slam_controller:
  node_management:
    exploration:
      # SLAM
      - graphslam

    racing:
      # SLAM
      - slam_mcl

    always:
      # SLAM
      - lap_counter

      # Control
      - front_wheel_feedback_control
      - pathplanning
      - path_builder
      - path_smoother

slam_mcl:
  path_to_map: "/ugr/car/map/slam/global"
lap_counter:
  finishpoint: [0, 0, 0]
  laps: 10
  distance_after: 4
speed:
  target: 1.0
  target_racing: 2.0
  LC_adaptive_velocity: False
  LC_max_acceleration: 0.5 # TO BE VERIFIED
  LC_min: 1.0
  LC_max: 4.0
pure_pursuit:
  change_index: True
  world_frame: "ugr/map"
  speed_start: 1
  speed_stop: 2
  distance_start: 1.5
  distance_stop: 3.3
front_wheel_feedback:
  change_index: True
  world_frame: "ugr/map"
  Kp: 0.8
  Ki: 0.01
  Kd: 0.01
mpc:
  change_index: True
  minimal_distance: 1.2
  world_frame: "ugr/map"
path_builder:
  enable_global_path: True
