slam_mcl:
  path_to_map: "/ugr/car/map/global"
loopclosure:
  finishpoint: [75, 0, 0]
map_publisher:
  map_pkg: "slam_simulator"
  map: "/maps/acceleration_75m.yaml"
pure_pursuit:
  change_index: False
  minimal_distance: 3
  world_frame: "ugr/map"
  speed:
    target: 3.0
path_publisher:
  package_path: "slam_controller"
  path: "/paths/straight_L75.yaml"
