slam_mcl:
  path_to_map: "/ugr/car/map/global"
loopclosure:
  finishpoint: [24, 0, 0]
map_publisher:
  map_pkg: "slam_simulator"
  map: "/maps/skidpad.yaml"
pure_pursuit:
  change_index: False
  world_frame: "ugr/map"
  speed:
    target: 10.0
mpc:
  change_index: False
  world_frame: "ugr/map"
  speed:
    target: 10.0
path_publisher:
  package_path: "slam_controller"
  path: "/paths/skidpad.yaml"
