repos:
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: ["--filter-files"]
    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black
            args: [--safe]
    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            args: ["--config=.flake8"]
            additional_dependencies: ['flake8-bugbear==21.4.3']
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v14.0.6
      hooks:
      - id: clang-format