networks:
  ros:
    driver: bridge

services:
  roscore:
    image: ugr-base
    networks:
      - ros
    restart: always
    tty: true
    build: .
    entrypoint: zsh -c 'source ~/.zshrc && roscore'
    ports:  
      - "11311:11311"
    volumes:
      - "./:/home/ugr/autonomous2023/:rw"
  rviz:
    image: ugr-base
    networks:
      - ros
    depends_on:
      - roscore
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    runtime: nvidia
    restart: always
    tty: true
    entrypoint: /bin/zsh -c 'source ~/.zshrc && rosrun rviz rviz -d ~/autonomous2023/ROS/rviz/ugr.rviz'
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - "./:/home/ugr/autonomous2023/:rw"
  builder:
    image: ugr-base
    tty: true
    entrypoint: /bin/zsh -c 'source ~/.zshrc && cd ~/autonomous2023/ROS && catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release && catkin build'
    volumes:
      - "./:/home/ugr/autonomous2023/:rw"
  dev-runner:
    image: ugr-base
    networks:
      - ros
    depends_on:
      - roscore
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    runtime: nvidia
    restart: always
    tty: true
    entrypoint: /bin/zsh
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - "./:/home/ugr/autonomous2023/:rw"
  prod-runner:
    image: ugr-base
    networks:
      - ros
    depends_on:
      - roscore
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    runtime: nvidia
    restart: always
    tty: true
    entrypoint: /bin/zsh -c "source ~/.zshrc && roslaunch /home/ugr/autonomous2023/ROS/launch/run.launch"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - "./:/home/ugr/autonomous2023/:rw"
