services:
  roscore:
    container_name: roscore
    image: ugr-base
    network_mode: "host"
    restart: always
    tty: true
    privileged: true
    entrypoint: zsh -c 'source ~/.zshrc && /home/ugr/autonomous2023/scripts/start_roscore.sh'
    volumes:
      - "./:/home/ugr/autonomous2023/:rw"
  rviz:
    container_name: rviz
    image: ugr-base
    network_mode: "host"
    privileged: true
    depends_on:
      - roscore
    environment:
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    restart: always
    tty: true
    entrypoint: /bin/zsh -c 'source ~/.zshrc && rosrun rviz rviz -d ~/autonomous2023/ROS/rviz/ugr.rviz'
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - "./:/home/ugr/autonomous2023/:rw"
  dev:
    container_name: dev
    image: ugr-base
    network_mode: "host"
    depends_on:
      - roscore
    environment:
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    restart: always
    tty: true
    privileged: true
    entrypoint: /bin/zsh
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - "./:/home/ugr/autonomous2023/:rw"
      - "./../rosbags:/home/ugr/rosbags/:rw"
      - "./../autonomous2023_binaries:/home/ugr/autonomous2023_binaries/:rw"
      - /dev:/dev