services:
  roscore:
    container_name: roscore
    image: ugr-base
    network_mode: "host"
    restart: always
    tty: true
    privileged: true
    build: .
    entrypoint: zsh -c 'source ~/.zshrc && roscore'
    ports:  
      - "11311:11311"
    volumes:
      - "./:/home/ugr/autonomous2023/:rw"
    environment:
      - ROS_HOSTNAME=$ROS_HOSTNAME
  rviz:
    container_name: rviz
    image: ugr-base
    network_mode: "host"
    depends_on:
      - roscore
    environment:
      - "ROS_MASTER_URI=$ROS_MASTER_URI"
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - ROS_HOSTNAME=$ROS_HOSTNAME
    runtime: nvidia
    restart: always
    tty: true
    entrypoint: /bin/zsh -c 'source ~/.zshrc && rosrun rviz rviz -d ~/autonomous2023/ROS/rviz/ugr.rviz'
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - "./:/home/ugr/autonomous2023/:rw"
  dev:
    container_name: dev
    image: ugr-base
    network_mode: "host"
    depends_on:
      - roscore
    environment:
      - "ROS_MASTER_URI=$ROS_MASTER_URI"
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - ROS_HOSTNAME=$ROS_HOSTNAME
    runtime: nvidia
    restart: always
    tty: true
    privileged: true
    entrypoint: /bin/zsh #-c 'source ~/.zshrc' && /bin/zsh
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - "./:/home/ugr/autonomous2023/:rw"
      - "./../rosbags:/home/ugr/rosbags/:rw"
      - "./../autonomous2023_binaries:/home/ugr/autonomous2023_binaries/:rw"
      - /dev:/dev
  builder:
    container_name: builder
    image: ugr-base
    tty: true
    entrypoint: /bin/zsh -c 'source ~/.zshrc && cd ~/autonomous2023/ROS && catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release && catkin build'
    volumes:
      - "./:/home/ugr/autonomous2023/:rw"
    environment:
      - ROS_HOSTNAME=$ROS_HOSTNAME
  clean:
    container_name: clean
    image: ugr-base
    tty: true
    entrypoint: /bin/zsh -c 'source ~/.zshrc && cd ~/autonomous2023/ROS && catkin clean'
    volumes:
      - "./:/home/ugr/autonomous2023/:rw"
    environment:
      - ROS_HOSTNAME=$ROS_HOSTNAME