mode: increment # The tuner mode: none, increment, list, multi

param:
  name: particle_count # Name of the parameter to tune
  file: /config/fastslam1.yaml # The location of the file where the parameter is located
  pkg: slam_fastslam # The package where the file is located
  index: None # The index of the parameter, if the parameter is a list (None if not)

list:
  values: [950, 1000] # List of values to try

increment:
  add_value: -100 # value to add to the parameter each time
  simulation_count: 2 # number of simulations to run

multi:
  - param:
      name: particle_count
      file: /config/fastslam1.yaml
      pkg: slam_fastslam
      index: None
    values: [1000, 2000, 500]
