# The track to be loaded
track: "layouts/track_08aug_1149.json"
# The distance by which the car drives every update
expand_dist: 0.5
# The distance the car can see in front
plan_dist: 12.0
# The amount of branches generated
max_iter: 100

# Early prune settings
# The maximum angle (rad) for a branch to be valid (sharper turns will be pruned prematurely)
max_angle_change: 1
# The radius around a obstacle (cone) where no path can be planned
safety_dist: 0.5

max_path_distance: 6

triangulation_min_var: 100
triangulation_var_threshold: 1.2

# Track randomisation arguments
colour_prob: 0.0  # The chance for a cones colour to be swapped
pos_prob: 0.0     # The chance for a cone to be moved
pos_radius: 0.0   # The maximum distance a cone will be moved

