observations_topic: "/ugr/car/observations/lidar"

slam_controller:
  node_management:
    always:
      # SLAM
      - slam_mcl
      - lap_counter
      - map_publisher

      - ecat_driver

      # Control
      - pure_pursuit_control
      - path_publisher
      # - path_smoother

slam_mcl:
  path_to_map: "/ugr/car/map/global"
lap_counter:
  finishpoint:
    x: 75
    y: 0
  distance_after: 0
  laps: 1
  finishRange: 3
map_publisher:
  map_pkg: "slam_simulator"
  map: "/maps/acceleration_map.yaml"
speed:
  target: 15
  LC_adaptive_velocity: False
pure_pursuit:
  change_index: False
  world_frame: "ugr/map"
  # Lookahead distance tuning parameters
  speed_start_racing: 6
  speed_stop_racing: 6
  distance_start_racing: 7
  distance_stop_racing: 7
front_wheel_feedback:
  change_index: False
  world_frame: "ugr/map"
  Kp: 0.8
  Ki: 0.01
  Kd: 0.01
mpc:
  change_index: False
  minimal_distance: 3
  world_frame: "ugr/map"
path_publisher:
  package_path: "path_publisher"
  path: "/paths/acceleration_cen.yaml"
