slam_controller:
  node_management:
    always:
      # SLAM
      - slam_mcl
      - lap_counter
      - map_publisher

      # Control
      - pure_pursuit_control
      - path_publisher
      - ecat_driver

slam_mcl:
  path_to_map: "/ugr/car/map/global"
lap_counter:
  finishpoint: [26, 0, 0]
map_publisher:
  map_pkg: "slam_simulator"
  map: "/maps/skidpad_map.yaml"
speed:
  target: 5.8
  LC_adaptive_velocity: False
pure_pursuit:
  change_index: False
  world_frame: "ugr/map"
  speed_start: 1
  speed_stop: 5.8
  distance_start: 4
  distance_stop: 5.5
front_wheel_feedback:
  change_index: False
  world_frame: "ugr/map"
  Kp: 0.8
  Ki: 0.01
  Kd: 0.01
mpc:
  change_index: False
  world_frame: "ugr/map"
path_publisher:
  package_path: "path_publisher"
  path: "/paths/skidpad_cen.yaml"
