observations_topic: "/ugr/car/observations/lidar"

slam_controller:
  node_management:
    exploration:
      # SLAM
      # - fastslam
      - graphslam

    racing:
      # SLAM
      - slam_mcl

    always:
      - ecat_driver

      # SLAM
      - lap_counter

      # Control
      - pure_pursuit_control
      - pathplanning
      # - boundary_estimation
      # - path_smoother
      - path_builder

slam_mcl:
  path_to_map: "/ugr/car/map/slam/global"
lap_counter:
  finishpoint:
    x: 0
    y: 0
  distance_after: 4
  laps: 10
  finishRange: 3
speed:
  target: 3
  target_racing: 6
  LC_adaptive_velocity: False
  LC_max_acceleration: 0.5 # TO BE VERIFIED
  LC_min: 1.0
  LC_max: 4.0
pure_pursuit:
  change_index: True
  world_frame: "ugr/map"
  # Lookahead distance tuning parameters
  # exploration
  speed_start_explo: 1
  speed_stop_explo: 7
  distance_start_explo: 5
  distance_stop_explo: 5
  # racing
  speed_start_racing: 1
  speed_stop_racing: 7
  distance_start_racing: 5
  distance_stop_racing: 5
front_wheel_feedback:
  change_index: True
  world_frame: "ugr/map"
  Kp: 0.8
  Ki: 0.01
  Kd: 0.01
mpc:
  change_index: True
  minimal_distance: 1.2
  world_frame: "ugr/map"
path_builder:
  enable_global_path: True
