autonomous_state:
  node_management:
    always:
      - slam_controller

orion_state:
  node_management:
    always:
      - can_cvrt_mc_right
      - can_cvrt_mc_left
      - can_cvrt_lv
      - iologik_aio
      - diobank_driver_can
    manual: 
      - pedal_mapper