ugr:
  car:
    steering:
      transmission: 0.25 # should be changed

front_wheel_feedback:
  cog_to_front_axle: 0.72 # should be changed

pure_pursuit:
  cog_to_front_axle: 0.72 # should be changed

autonomous_state:
  node_management:
    always:
      - slam_controller

orion_state:
  node_management:
    driverless:
      - autonomous_state
    manual:
      - manual_state
      
