autonomous_state:
  node_management:
    always:
      - slam_controller

orion_state:
  node_management:
    always:
      # - can_cvrt_mc
      - can_cvrt_lv
      - iologik_aio
      - diobank_driver_can
    # driverless:
    #   - autonomous_state
