# Use this file to override paramters for Pegasus
ugr:
  car:
    steering:
      transmission: 0.25
    wheel:
      radius: 0.1
    cog_to_front_axle: 0.72
    wheelbase: 0.72

autonomous_state:
  node_management:
    always:
      - slam_controller

pure_pursuit:
  speed_start: 1
  speed_stop: 2
  distance_start: 1.5
  distance_stop: 3.3 

front_wheel_feedback:
  Kp: 0.8
  Ki: 0.01
  Kd: 0.01