# Use this file to override paramters for simulation
ugr:
  car:
    steering:
      transmission: 1.0
    wheel:
      radius: 0.2
    cog_to_front_axle: 0.90
    wheelbase: 1.60

autonomous_state:
  node_management:
    always:
      - slam_controller
