slam_controller:
  node_management:
    always:
      # SLAM
      - slam_mcl
      - lap_counter
      - map_publisher

      # Control
      - front_wheel_feedback_control
      - path_smoother
      - path_publisher

slam_mcl:
  path_to_map: "/ugr/car/map/global"
lap_counter:
  finishpoint_x: 75
  finishpoint_y: 0
  finishpoint_z: 0
  laps: 1
  distance_after: 0
map_publisher:
  map_pkg: "slam_simulator"
  map: "/maps/acceleration_75m.yaml"
speed:
  target: 10.0
  LC_adaptive_velocity: False
pure_pursuit:
  change_index: False
  world_frame: "ugr/map"
  speed_start: 3
  speed_stop: 12
  distance_start: 3
  distance_stop: 5
front_wheel_feedback:
  change_index: False
  world_frame: "ugr/map"
  Kp: 1.0
  Ki: 0.01
  Kd: 0.01
mpc:
  change_index: False
  minimal_distance: 3
  world_frame: "ugr/map"
path_publisher:
  package_path: "path_publisher"
  path: "/paths/straight_L75.yaml"
