slam_controller:
  node_management:
    exploration:
      # SLAM
      - graphslam

    always:
      # SLAM
      - lap_counter

      # Control
      - front_wheel_feedback_control
      - pathplanning
      - path_builder
      - path_smoother

slam_mcl:
  path_to_map: "/ugr/car/map/slam/global"
lap_counter:
  finishpoint_x: 0
  finishpoint_y: 0
  finishpoint_z: 0
  laps: 10
  distance_after: 0
speed:
  target: 2.0
  LC_adaptive_velocity: False
front_wheel_feedback:
  change_index: True
  world_frame: "ugr/map"
  Kp: 1.5
  Ki: 0.01
  Kd: 0.01
pure_pursuit:
  change_index: True
  world_frame: "ugr/map"
  speed_start: 3
  speed_stop: 12
  distance_start: 3
  distance_stop: 5
mpc:
  change_index: True
  world_frame: "ugr/map"
path_builder:
  enable_global_path: False
