slam_controller:
  node_management:
    exploration:
      # SLAM
      - graphslam

    always:
      # SLAM
      - loopclosure

      # Control
      - front_wheel_feedback_control
      - pathplanning

slam_mcl:
  path_to_map: "/ugr/car/map/slam/global"
loopclosure:
  finishpoint: [0, 0, 0]
speed:
  target: 2.0
  LC_adaptive_velocity: False
pure_pursuit:
  change_index: True
  world_frame: "ugr/map"
front_wheel_feedback:
  change_index: True
  world_frame: "ugr/map"
mpc:
  change_index: True
  world_frame: "ugr/map"
