slam_controller:
  node_management:
    always:
      # SLAM
      - slam_mcl
      - lap_counter
      - map_publisher

      # Control
      - front_wheel_feedback_control
      # - path_smoother
      - path_publisher

slam_mcl:
  path_to_map: "/ugr/car/map/global"
lap_counter:
  finishpoint:
    x: 0
    y: 16 # should be 2 * turn radius
  laps: 1
  distance_after: 0
  finishRange: 3
map_publisher:
  map_pkg: "slam_simulator"
  map: "/maps/map_dvsv.yaml"
speed:
  target: 10.0
  LC_adaptive_velocity: False
front_wheel_feedback:
  change_index: False
  world_frame: "ugr/map"
  Kp: 1.8
  Ki: 0.01
  Kd: 0.01
pure_pursuit:
  change_index: False
  world_frame: "ugr/map"
  # Lookahead distance tuning parameters
  speed_start_racing: 3
  speed_stop_racing: 12
  distance_start_racing: 3
  distance_stop_racing: 5
mpc:
  change_index: False
  minimal_distance: 3
  world_frame: "ugr/map"
path_publisher:
  package_path: "path_publisher"
  path: "/paths/centerline_dvsv.yaml"
