slam_controller:
  node_management:
    always:
      # SLAM
      - slam_mcl
      - lap_counter
      - map_publisher

      # Control
      - front_wheel_feedback_control
      - path_publisher
      - path_smoother

slam_mcl:
  path_to_map: "/ugr/car/map/global"
lap_counter:
  finishpoint: [24, 0, 0]
map_publisher:
  map_pkg: "slam_simulator"
  map: "/maps/skidpad.yaml"
speed:
  target: 10.0
  LC_adaptive_velocity: False
front_wheel_feedback:
  change_index: False
  world_frame: "ugr/map"
pure_pursuit:
  change_index: False
  world_frame: "ugr/map"
mpc:
  change_index: False
  world_frame: "ugr/map"
path_publisher:
  package_path: "path_publisher"
  path: "/paths/skidpad.yaml"
