slam_controller:
  node_management:
    exploration:
      # SLAM
      - graphslam

    racing:
      # SLAM
      - slam_mcl

      # Control
      # - minimum_curvature

    always:
      # SLAM
      - lap_counter

      # Control
      - front_wheel_feedback_control
      - pathplanning
      # - path_smoother

slam_mcl:
  path_to_map: "/ugr/car/map/slam/global"
lap_counter:
  finishpoint: [0, 0, 0]
speed:
  target: 2.0
  target_racing: 10.0
  LC_adaptive_velocity: False
  LC_max_acceleration: 2.0
  LC_min: 3.0
  LC_max: 15.0
front_wheel_feedback:
  change_index: True
  world_frame: "ugr/map"
  Kp: 1.5
  Ki: 0.01
  Kd: 0.01
pure_pursuit:
  change_index: True
  world_frame: "ugr/map"
  speed_start: 3
  speed_stop: 12
  distance_start: 3
  distance_stop: 5
mpc:
  change_index: True
  minimal_distance: 1.2
  world_frame: "ugr/map"
