slam_controller:
  node_management:
    exploration:
      # SLAM
      # - graphslam
      - fastslam

    racing:

      # SLAM
      - slam_mcl

    always:
      # SLAM
      - loopclosure

      # Control
      - front_wheel_feedback_control
      - pathplanning

slam_mcl:
  path_to_map: "/ugr/car/map/slam/global"
loopclosure:
  finishpoint: [0, 0, 0]
speed:
  target: 2.0
  target_racing: 10.0
pure_pursuit:
  change_index: True
  minimal_distance: 1.2
  world_frame: "ugr/map"
mpc:
  change_index: True
  minimal_distance: 1.2
  world_frame: "ugr/map"
