name: ros-build-modules

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Build Docker image (nogpu)
        run: ./run build-nogpu

      - name: Build stack
        run: ./run build-stack