#
# This workflow runs all the time. 
# Checks if our repository can be build (both Docker and ROS stack)
# and then runs some simulations to functionally validate our stack
#

name: ugr-validation-workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build Docker image (nogpu)
        run: ./run build-nogpu

      - name: Build stack
        run: ./run build-stack
  simulate-skidpad:
    runs-on: self-hosted
    needs: [build]
    steps:

      - name: Run Skidpad simulation and supervise
        run: | 
          ./run stop
          ./run set-car simulation
          ./run set-random-roscore-port
          ./run start-headless
          ./run simulation skidpad skidpad
          docker exec dev /bin/zsh -c "source ~/.zshrc && rosrun autonomous_state state_supervisor.py _timeout:=60"
          ./run stop
  simulate-acceleration:
    runs-on: self-hosted
    needs: [build]
    steps:

      - name: Run acceleration simulation and supervise
        run: | 
          ./run stop
          ./run set-car simulation
          ./run set-random-roscore-port
          ./run start-headless
          ./run simulation acceleration acceleration_75m
          docker exec dev /bin/zsh -c "source ~/.zshrc && rosrun autonomous_state state_supervisor.py _timeout:=30"
          ./run stop